
import { Language, ProductDef } from './types';

export const LANGUAGES: { [key in Language]: { flag: string; name: string } } = {
  PT: { flag: "🇵🇹", name: "Português" },
  EN: { flag: "🇬🇧", name: "English" },
  ES: { flag: "🇪🇸", name: "Español" },
  FR: { flag: "🇫🇷", name: "Français" },
  DE: { flag: "🇩🇪", name: "Deutsch" },
};

export const CATEGORIES_MAP: { [key: string]: { [key in Language]: string } & { icon: string } } = {
  arroz_massa: { PT: "Arroz e Massas", EN: "Rice & Pasta", ES: "Arroz y Pasta", FR: "Riz et Pâtes", DE: "Reis & Nudeln", icon: "🍝" },
  azeites: { PT: "Condimentos", EN: "Condiments", ES: "Condimentos", FR: "Condiments", DE: "Würzmittel", icon: "🧂" },
  bebidas: { PT: "Bebidas", EN: "Drinks", ES: "Bebidas", FR: "Boissons", DE: "Getränke", icon: "🥤" },
  congelados: { PT: "Congelados", EN: "Frozen", ES: "Congelados", FR: "Surgelés", DE: "Tiefkühl", icon: "❄️" },
  conservas: { PT: "Conservas", EN: "Canned", ES: "Conservas", FR: "Conserves", DE: "Konserven", icon: "🥫" },
  doces: { PT: "Doces", EN: "Sweets", ES: "Dulces", FR: "Sucreries", DE: "Süßigkeiten", icon: "🍫" },
  fruta: { PT: "Fruta", EN: "Fruit", ES: "Fruta", FR: "Fruits", DE: "Obst", icon: "🍎" },
  higiene: { PT: "Higiene", EN: "Hygiene", ES: "Higiene", FR: "Hygiène", DE: "Hygiene", icon: "🧴" },
  laticinios: { PT: "Laticínios", EN: "Dairy", ES: "Lácteos", FR: "Produits Laitiers", DE: "Milchprodukte", icon: "🧀" },
  limpeza: { PT: "Limpeza", EN: "Cleaning", ES: "Limpieza", FR: "Nettoyage", DE: "Reinigung", icon: "🧹" },
  padaria_pastelaria: { PT: "Padaria", EN: "Bakery", ES: "Panadería", FR: "Boulangerie", DE: "Bäckerei", icon: "🥖" },
  peixaria: { PT: "Peixaria", EN: "Fish Market", ES: "Pescadería", FR: "Poissonnerie", DE: "Fischmarkt", icon: "🐟" },
  talho: { PT: "Talho", EN: "Butcher", ES: "Carnicería", FR: "Boucherie", DE: "Metzgerei", icon: "🥩" },
  vegetais: { PT: "Vegetais", EN: "Vegetables", ES: "Vegetales", FR: "Légumes", DE: "Gemüse", icon: "🥦" },
  outros: { PT: "Outros", EN: "Others", ES: "Otros", FR: "Autres", DE: "Andere", icon: "📦" }
};

export const DICTIONARY: { [key in Language]: any } = {
  PT: {
    welcome: "Bem-vindo", enterName: "O Teu Nome", enterCode: "Código da Família",
    start: "Começar", back: "Voltar", logout: "Sair",
    panel: "Despensa", shop: "Catálogo", cook: "Chef IA", list: "Lista", plan: "Plano", settings: "Perfil",
    search: "O que procuras?", updatedBy: "Por:",
    days: "dias", months: "meses", rest: "Durabilidade:", consumeTitle: "Consumo Regular:",
    finish: "Finalizar Receita", discard: "Rejeitar", recipeIng: "Ingredientes Necessários",
    addManual: "Novo Produto", addCategory: "Nova Categoria", confirm: "Confirmar", cancel: "Cancelar",
    delete: "Eliminar", buy: "Comprar", buyAll: "Comprar Tudo", bought: "Comprado",
    translating: "Chef a pensar...", translatingRecipe: "A criar magia culinária...",
    manualMeal: "Refeição Manual", openRecipe: "Ver Receita",
    weeklyPlan: "Plano Semanal", servings: "Pessoas", logoutConfirm: "Tens a certeza que queres sair?",
    pantryRemoveText: "O item será removido do stock mas continuará no catálogo.",
    save: "Guardar", typeHere: "Escreve aqui...",
    wandTip: "Escreve o nome e clica na varinha!",
    selectCat: "Seleciona a Categoria",
    meals: ["Pequeno-Almoço", "Lanche Manhã", "Almoço", "Lanche Tarde", "Jantar"],
    daysWeek: ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"],
    dietary: "Restrições Alimentares",
    dietaryPlaceholder: "Ex: Vegan, Sem Glúten...",
    householdName: "Nome da Despensa",
    expiryDate: "Validade",
    expiresIn: "Caduca em",
    expired: "Expirou!",
    manualOptions: { cooked: "Cozinhei (Gastar Stock)", out: "Comi Fora (Manter Stock)" },
    pantryName: "Minha Despensa"
  },
  EN: {
    welcome: "Welcome", enterName: "Your Name", enterCode: "Family Code",
    start: "Start", back: "Back", logout: "Logout",
    panel: "Pantry", shop: "Catalog", cook: "AI Chef", list: "List", plan: "Plan", settings: "Profile",
    search: "Search...", updatedBy: "By:",
    days: "days", months: "months", rest: "Lasts for:", consumeTitle: "Regular Consumption:",
    finish: "Finish Recipe", discard: "Discard", recipeIng: "Ingredients Needed",
    addManual: "New Item", addCategory: "New Category", confirm: "Confirm", cancel: "Cancel",
    delete: "Delete", buy: "Buy", buyAll: "Buy All", bought: "Bought",
    translating: "Chef thinking...", translatingRecipe: "Creating culinary magic...",
    manualMeal: "Manual Meal", openRecipe: "View Recipe",
    weeklyPlan: "Weekly Plan", servings: "People", logoutConfirm: "Are you sure you want to logout?",
    pantryRemoveText: "Item will be removed from stock but kept in catalog.",
    save: "Save", typeHere: "Type here...",
    wandTip: "Type name and click the wand!",
    selectCat: "Select Category",
    meals: ["Breakfast", "Morning Snack", "Lunch", "Afternoon Snack", "Dinner"],
    daysWeek: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    dietary: "Dietary Restrictions",
    dietaryPlaceholder: "Ex: Vegan, Gluten Free...",
    householdName: "Pantry Name",
    expiryDate: "Expiry Date",
    expiresIn: "Expires in",
    expired: "Expired!",
    manualOptions: { cooked: "Cooked (Use Stock)", out: "Ate Out (Keep Stock)" },
    pantryName: "My Pantry"
  },
  ES: {
    welcome: "Bienvenido", enterName: "Tu Nombre", enterCode: "Código de Familia",
    start: "Empezar", back: "Volver", logout: "Salir",
    panel: "Despensa", shop: "Catálogo", cook: "Chef IA", list: "Lista", plan: "Plan", settings: "Perfil",
    search: "Buscar...", updatedBy: "Por:",
    days: "días", months: "meses", rest: "Duración:", consumeTitle: "Consumo:",
    finish: "Finalizar", discard: "Rechazar", recipeIng: "Ingredientes",
    addManual: "Nuevo Item", addCategory: "Nueva Categoría", confirm: "Confirmar", cancel: "Cancelar",
    delete: "Eliminar", buy: "Comprar", buyAll: "Comprar Todo", bought: "Comprado",
    translating: "Chef pensando...", translatingRecipe: "Creando magia culinaria...",
    manualMeal: "Comida Manual", openRecipe: "Ver Receta",
    weeklyPlan: "Plan Semanal", servings: "Personas", logoutConfirm: "¿Seguro que quieres salir?",
    pantryRemoveText: "El ítem se elimina del stock pero sigue en el catálogo.",
    save: "Guardar", typeHere: "Escribe aquí...",
    wandTip: "¡Escribe y usa la varita!",
    selectCat: "Selecciona Categoría",
    meals: ["Desayuno", "Merienda", "Almuerzo", "Merienda", "Cena"],
    daysWeek: ["Dom", "Lun", "Mar", "Mié", "Jue", "Vie", "Sáb"],
    dietary: "Restricciones Alimentarias",
    dietaryPlaceholder: "Ej: Vegano, Sin Gluten...",
    householdName: "Nombre Despensa",
    expiryDate: "Caducidad",
    expiresIn: "Caduca en",
    expired: "¡Caducado!",
    manualOptions: { cooked: "Cociné (Gastar)", out: "Comí Fuera (Mantener)" },
    pantryName: "Mi Despensa"
  },
  FR: {
    welcome: "Bienvenue", enterName: "Votre Nom", enterCode: "Code Famille",
    start: "Démarrer", back: "Retour", logout: "Déconnexion",
    panel: "Cellier", shop: "Catalogue", cook: "Chef IA", list: "Liste", plan: "Plan", settings: "Profil",
    search: "Rechercher...", updatedBy: "Par:",
    days: "jours", months: "mois", rest: "Durée:", consumeTitle: "Consommation:",
    finish: "Terminer", discard: "Rejeter", recipeIng: "Ingrédients",
    addManual: "Nouvel Article", addCategory: "Nouvelle Catégorie", confirm: "Confirmer", cancel: "Annuler",
    delete: "Supprimer", buy: "Acheter", buyAll: "Tout Acheter", bought: "Acheté",
    translating: "Le Chef réfléchit...", translatingRecipe: "Création de magie culinaire...",
    manualMeal: "Repas Manuel", openRecipe: "Voir Recette",
    weeklyPlan: "Plan Hebdo", servings: "Personnes", logoutConfirm: "Voulez-vous vraiment sortir?",
    pantryRemoveText: "L'article sera retiré du stock mais restera au catalogue.",
    save: "Sauver", typeHere: "Écrivez ici...",
    wandTip: "Tapez le nom et cliquez sur la baguette!",
    selectCat: "Choisir Catégorie",
    meals: ["Petit Déj", "Collation", "Déjeuner", "Goûter", "Dîner"],
    daysWeek: ["Dim", "Lun", "Mar", "Mer", "Jeu", "Ven", "Sam"],
    dietary: "Restrictions Alimentaires",
    dietaryPlaceholder: "Ex: Végan, Sans Gluten...",
    householdName: "Nom du Cellier",
    expiryDate: "Date d'expiration",
    expiresIn: "Expire dans",
    expired: "Expiré!",
    manualOptions: { cooked: "Cuisiné (Utiliser Stock)", out: "Mangé Dehors (Garder Stock)" },
    pantryName: "Mon Cellier"
  },
  DE: {
    welcome: "Willkommen", enterName: "Dein Name", enterCode: "Familiencode",
    start: "Start", back: "Zurück", logout: "Abmelden",
    panel: "Vorrat", shop: "Katalog", cook: "KI Chef", list: "Liste", plan: "Plan", settings: "Profil",
    search: "Suche...", updatedBy: "Von:",
    days: "Tage", months: "Monate", rest: "Dauer:", consumeTitle: "Verbrauch:",
    finish: "Fertig", discard: "Ablehnen", recipeIng: "Zutaten",
    addManual: "Neu", addCategory: "Neue Kategorie", confirm: "Bestätigen", cancel: "Abbrechen",
    delete: "Löschen", buy: "Kaufen", buyAll: "Alles Kaufen", bought: "Gekauft",
    translating: "Chef denkt nach...", translatingRecipe: "Kulinarische Magie erzeugen...",
    manualMeal: "Manuell", openRecipe: "Rezept",
    weeklyPlan: "Wochenplan", servings: "Personen", logoutConfirm: "Möchten Sie sich wirklich abmelden?",
    pantryRemoveText: "Artikel wird aus dem Bestand entfernt, bleibt aber im Katalog.",
    save: "Speichern", typeHere: "Hier tippen...",
    wandTip: "Name eingeben und Zauberstab klicken!",
    selectCat: "Kategorie wählen",
    meals: ["Frühstück", "Snack", "Mittagessen", "Snack", "Abendessen"],
    daysWeek: ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"],
    dietary: "Ernährungsbedürfnisse",
    dietaryPlaceholder: "Z.B. Vegan, Glutenfrei...",
    householdName: "Vorratsname",
    expiryDate: "Verfallsdatum",
    expiresIn: "Läuft ab in",
    expired: "Abgelaufen!",
    manualOptions: { cooked: "Gekocht (Bestand nutzen)", out: "Auswärts (Bestand behalten)" },
    pantryName: "Mein Vorrat"
  }
};

export const FULL_CATALOG: ProductDef[] = [
  // --- VESTUÁRIO ---
  { id: 'meias', names: { PT: 'Meias', EN: 'Socks', ES: 'Calcetines', FR: 'Chaussettes', DE: 'Socken' }, icon: '🧦', unit: 'par', category: 'outros' },
  { id: 'sapatos', names: { PT: 'Sapatos', EN: 'Shoes', ES: 'Zapatos', FR: 'Chaussures', DE: 'Schuhe' }, icon: '👟', unit: 'par', category: 'outros' },
  { id: 'tshirt', names: { PT: 'T-Shirt', EN: 'T-Shirt', ES: 'Camiseta', FR: 'T-shirt', DE: 'T-Shirt' }, icon: '👕', unit: 'unid', category: 'outros' },
  { id: 'calcas', names: { PT: 'Calças', EN: 'Pants', ES: 'Pantalones', FR: 'Pantalon', DE: 'Hose' }, icon: '👖', unit: 'unid', category: 'outros' },
  { id: 'casaco', names: { PT: 'Casaco', EN: 'Jacket', ES: 'Chaqueta', FR: 'Veste', DE: 'Jacke' }, icon: '🧥', unit: 'unid', category: 'outros' },
  { id: 'vestido', names: { PT: 'Vestido', EN: 'Dress', ES: 'Vestido', FR: 'Robe', DE: 'Kleid' }, icon: '👗', unit: 'unid', category: 'outros' },
  { id: 'roupa_int', names: { PT: 'Roupa Interior', EN: 'Underwear', ES: 'Ropa Interior', FR: 'Sous-vêtements', DE: 'Unterwäsche' }, icon: '👙', unit: 'unid', category: 'outros' },
  { id: 'pijama', names: { PT: 'Pijama', EN: 'Pajamas', ES: 'Pijama', FR: 'Pyjama', DE: 'Schlafanzug' }, icon: '🛌', unit: 'unid', category: 'outros' },
  { id: 'acessorios', names: { PT: 'Acessórios Inverno', EN: 'Winter Accessories', ES: 'Accesorios Invierno', FR: 'Accessoires Hiver', DE: 'Winterzubehör' }, icon: '🧣', unit: 'unid', category: 'outros' },
  { id: 'fato', names: { PT: 'Fato/Gravata', EN: 'Suit/Tie', ES: 'Traje/Corbata', FR: 'Costume/Cravate', DE: 'Anzug/Krawatte' }, icon: '👔', unit: 'unid', category: 'outros' },

  // --- CASA / ELETRÓNICA ---
  { id: 'pilhas', names: { PT: 'Pilhas', EN: 'Batteries', ES: 'Pilas', FR: 'Piles', DE: 'Batterien' }, icon: '🔋', unit: 'emb', category: 'outros' },
  { id: 'lampadas', names: { PT: 'Lâmpadas', EN: 'Light Bulbs', ES: 'Bombillas', FR: 'Ampoules', DE: 'Glühbirnen' }, icon: '💡', unit: 'unid', category: 'outros' },
  { id: 'velas', names: { PT: 'Velas', EN: 'Candles', ES: 'Velas', FR: 'Bougies', DE: 'Kerzen' }, icon: '🕯️', unit: 'unid', category: 'outros' },
  { id: 'livros', names: { PT: 'Livros/Revistas', EN: 'Books', ES: 'Libros', FR: 'Livres', DE: 'Bücher' }, icon: '📚', unit: 'unid', category: 'outros' },
  { id: 'escrita', names: { PT: 'Material Escrita', EN: 'Writing Tools', ES: 'Material Escritura', FR: 'Matériel Écriture', DE: 'Schreibwaren' }, icon: '🖊️', unit: 'unid', category: 'outros' },
  { id: 'escritorio', names: { PT: 'Material Escritório', EN: 'Office Supplies', ES: 'Material Oficina', FR: 'Fournitures Bureau', DE: 'Bürobedarf' }, icon: '✂️', unit: 'unid', category: 'outros' },
  { id: 'ferramentas', names: { PT: 'Ferramentas', EN: 'Tools', ES: 'Herramientas', FR: 'Outils', DE: 'Werkzeuge' }, icon: '🛠️', unit: 'unid', category: 'outros' },

  // --- FARMÁCIA ---
  { id: 'medicamentos', names: { PT: 'Medicamentos', EN: 'Medicine', ES: 'Medicamentos', FR: 'Médicaments', DE: 'Medikamente' }, icon: '💊', unit: 'emb', category: 'higiene' },
  { id: 'primeiros_socorros', names: { PT: 'Primeiros Socorros', EN: 'First Aid', ES: 'Primeros Auxilios', FR: 'Premiers Secours', DE: 'Erste Hilfe' }, icon: '🩹', unit: 'emb', category: 'higiene' },
  { id: 'termometro', names: { PT: 'Termómetro', EN: 'Thermometer', ES: 'Termómetro', FR: 'Thermomètre', DE: 'Thermometer' }, icon: '🌡️', unit: 'unid', category: 'higiene' },
  { id: 'preservativos', names: { PT: 'Preservativos', EN: 'Condoms', ES: 'Condones', FR: 'Préservatifs', DE: 'Kondome' }, icon: '🛡️', unit: 'emb', category: 'higiene' },

  // --- FRUTA ---
  { id: 'pera', names: { PT: 'Pêra', EN: 'Pear', ES: 'Pera', FR: 'Poire', DE: 'Birne' }, icon: '🍐', unit: 'kg', category: 'fruta' },
  { id: 'maca', names: { PT: 'Maçã', EN: 'Apple', ES: 'Manzana', FR: 'Pomme', DE: 'Apfel' }, icon: '🍎', unit: 'kg', category: 'fruta' },
  { id: 'banana', names: { PT: 'Banana', EN: 'Banana', ES: 'Plátano', FR: 'Banane', DE: 'Banane' }, icon: '🍌', unit: 'kg', category: 'fruta' },
  { id: 'laranja', names: { PT: 'Laranja', EN: 'Orange', ES: 'Naranja', FR: 'Orange', DE: 'Orange' }, icon: '🍊', unit: 'kg', category: 'fruta' },
  { id: 'limao', names: { PT: 'Limão', EN: 'Lemon', ES: 'Limón', FR: 'Citron', DE: 'Zitrone' }, icon: '🍋', unit: 'kg', category: 'fruta' },
  { id: 'uva', names: { PT: 'Uva', EN: 'Grapes', ES: 'Uvas', FR: 'Raisins', DE: 'Trauben' }, icon: '🍇', unit: 'kg', category: 'fruta' },
  { id: 'morangos', names: { PT: 'Morangos', EN: 'Strawberries', ES: 'Fresas', FR: 'Fraises', DE: 'Erdbeeren' }, icon: '🍓', unit: 'emb', category: 'fruta' },
  { id: 'melancia', names: { PT: 'Melancia', EN: 'Watermelon', ES: 'Sandía', FR: 'Pastèque', DE: 'Wassermelone' }, icon: '🍉', unit: 'kg', category: 'fruta' },
  { id: 'melao', names: { PT: 'Melão', EN: 'Melon', ES: 'Melón', FR: 'Melon', DE: 'Melone' }, icon: '🍈', unit: 'kg', category: 'fruta' },
  { id: 'pessego', names: { PT: 'Pêssego', EN: 'Peach', ES: 'Melocotón', FR: 'Pêche', DE: 'Pfirsich' }, icon: '🍑', unit: 'kg', category: 'fruta' },
  { id: 'ananas', names: { PT: 'Ananás', EN: 'Pineapple', ES: 'Piña', FR: 'Ananas', DE: 'Ananas' }, icon: '🍍', unit: 'unid', category: 'fruta' },
  { id: 'kiwi', names: { PT: 'Kiwi', EN: 'Kiwi', ES: 'Kiwi', FR: 'Kiwi', DE: 'Kiwi' }, icon: '🥝', unit: 'kg', category: 'fruta' },
  { id: 'cereja', names: { PT: 'Cereja', EN: 'Cherry', ES: 'Cereza', FR: 'Cerise', DE: 'Kirsche' }, icon: '🍒', unit: 'kg', category: 'fruta' },
  { id: 'manga', names: { PT: 'Manga', EN: 'Mango', ES: 'Mango', FR: 'Mangue', DE: 'Mango' }, icon: '🥭', unit: 'kg', category: 'fruta' },
  { id: 'abacate', names: { PT: 'Abacate', EN: 'Avocado', ES: 'Aguacate', FR: 'Avocat', DE: 'Avocado' }, icon: '🥑', unit: 'unid', category: 'fruta' },
  { id: 'coco', names: { PT: 'Coco', EN: 'Coconut', ES: 'Coco', FR: 'Noix de Coco', DE: 'Kokosnuss' }, icon: '🥥', unit: 'unid', category: 'fruta' },

  // --- VEGETAIS ---
  { id: 'batata', names: { PT: 'Batata', EN: 'Potato', ES: 'Patata', FR: 'Pomme de terre', DE: 'Kartoffel' }, icon: '🥔', unit: 'kg', category: 'vegetais' },
  { id: 'cenoura', names: { PT: 'Cenoura', EN: 'Carrot', ES: 'Zanahoria', FR: 'Carotte', DE: 'Karotte' }, icon: '🥕', unit: 'kg', category: 'vegetais' },
  { id: 'cebola', names: { PT: 'Cebola', EN: 'Onion', ES: 'Cebolla', FR: 'Oignon', DE: 'Zwiebel' }, icon: '🧅', unit: 'kg', category: 'vegetais' },
  { id: 'alho', names: { PT: 'Alho', EN: 'Garlic', ES: 'Ajo', FR: 'Ail', DE: 'Knoblauch' }, icon: '🧄', unit: 'unid', category: 'vegetais' },
  { id: 'tomate', names: { PT: 'Tomate', EN: 'Tomato', ES: 'Tomate', FR: 'Tomate', DE: 'Tomate' }, icon: '🍅', unit: 'kg', category: 'vegetais' },
  { id: 'alface', names: { PT: 'Alface', EN: 'Lettuce', ES: 'Lechuga', FR: 'Laitue', DE: 'Salat' }, icon: '🥬', unit: 'unid', category: 'vegetais' },
  { id: 'brocolos', names: { PT: 'Brócolos', EN: 'Broccoli', ES: 'Brócoli', FR: 'Brocoli', DE: 'Brokkoli' }, icon: '🥦', unit: 'kg', category: 'vegetais' },
  { id: 'pepino', names: { PT: 'Pepino', EN: 'Cucumber', ES: 'Pepino', FR: 'Concombre', DE: 'Gurke' }, icon: '🥒', unit: 'unid', category: 'vegetais' },
  { id: 'pimento', names: { PT: 'Pimento', EN: 'Pepper', ES: 'Pimiento', FR: 'Poivron', DE: 'Paprika' }, icon: '🫑', unit: 'unid', category: 'vegetais' },
  { id: 'milho', names: { PT: 'Milho', EN: 'Corn', ES: 'Maíz', FR: 'Maïs', DE: 'Mais' }, icon: '🌽', unit: 'emb', category: 'vegetais' },
  { id: 'cogumelos', names: { PT: 'Cogumelos', EN: 'Mushrooms', ES: 'Champiñones', FR: 'Champignons', DE: 'Pilze' }, icon: '🍄', unit: 'kg', category: 'vegetais' },
  { id: 'beringela', names: { PT: 'Beringela', EN: 'Eggplant', ES: 'Berenjena', FR: 'Aubergine', DE: 'Aubergine' }, icon: '🍆', unit: 'kg', category: 'vegetais' },
  { id: 'abobora', names: { PT: 'Abóbora', EN: 'Pumpkin', ES: 'Calabaza', FR: 'Citrouille', DE: 'Kürbis' }, icon: '🎃', unit: 'kg', category: 'vegetais' },

  // --- CARNE ---
  { id: 'frango', names: { PT: 'Frango', EN: 'Chicken', ES: 'Pollo', FR: 'Poulet', DE: 'Hähnchen' }, icon: '🍗', unit: 'kg', category: 'talho' },
  { id: 'carne_vaca', names: { PT: 'Carne Vaca', EN: 'Beef', ES: 'Ternera', FR: 'Bœuf', DE: 'Rindfleisch' }, icon: '🥩', unit: 'kg', category: 'talho' },
  { id: 'carne_porco', names: { PT: 'Carne Porco', EN: 'Pork', ES: 'Cerdo', FR: 'Porc', DE: 'Schweinefleisch' }, icon: '🐖', unit: 'kg', category: 'talho' },
  { id: 'salsichas', names: { PT: 'Salsichas/Bacon', EN: 'Sausages/Bacon', ES: 'Salchichas/Bacon', FR: 'Saucisses/Bacon', DE: 'Würstchen/Speck' }, icon: '🥓', unit: 'emb', category: 'talho' },

  // --- PEIXE ---
  { id: 'peixe', names: { PT: 'Peixe Fresco', EN: 'Fresh Fish', ES: 'Pescado Fresco', FR: 'Poisson Frais', DE: 'Frischer Fisch' }, icon: '🐟', unit: 'kg', category: 'peixaria' },
  { id: 'marisco', names: { PT: 'Marisco', EN: 'Seafood', ES: 'Marisco', FR: 'Fruits de Mer', DE: 'Meeresfrüchte' }, icon: '🦐', unit: 'kg', category: 'peixaria' },
  { id: 'lulas', names: { PT: 'Lulas/Polvo', EN: 'Squid/Octopus', ES: 'Calamar/Pulpo', FR: 'Calamar/Poulpe', DE: 'Tintenfisch/Oktopus' }, icon: '🦑', unit: 'kg', category: 'peixaria' },
  { id: 'conservas_peixe', names: { PT: 'Conservas Peixe', EN: 'Canned Fish', ES: 'Conservas Pescado', FR: 'Conserves Poisson', DE: 'Fischkonserven' }, icon: '🥫', unit: 'emb', category: 'conservas' },
  { id: 'sushi', names: { PT: 'Sushi', EN: 'Sushi', ES: 'Sushi', FR: 'Sushi', DE: 'Sushi' }, icon: '🍣', unit: 'emb', category: 'peixaria' },

  // --- PADARIA ---
  { id: 'pao', names: { PT: 'Pão', EN: 'Bread', ES: 'Pan', FR: 'Pain', DE: 'Brot' }, icon: '🥖', unit: 'unid', category: 'padaria_pastelaria' },
  { id: 'pao_forma', names: { PT: 'Pão de Forma', EN: 'Sliced Bread', ES: 'Pan de Molde', FR: 'Pain de Mie', DE: 'Toastbrot' }, icon: '🍞', unit: 'emb', category: 'padaria_pastelaria' },
  { id: 'pastelaria', names: { PT: 'Pastelaria', EN: 'Pastry', ES: 'Pastelería', FR: 'Pâtisserie', DE: 'Gebäck' }, icon: '🥐', unit: 'unid', category: 'padaria_pastelaria' },
  { id: 'bolo', names: { PT: 'Bolo', EN: 'Cake', ES: 'Pastel', FR: 'Gâteau', DE: 'Kuchen' }, icon: '🍰', unit: 'unid', category: 'doces' },
  { id: 'bolachas', names: { PT: 'Bolachas', EN: 'Cookies', ES: 'Galletas', FR: 'Biscuits', DE: 'Kekse' }, icon: '🍪', unit: 'emb', category: 'padaria_pastelaria' },
  { id: 'farinha', names: { PT: 'Farinha', EN: 'Flour', ES: 'Harina', FR: 'Farine', DE: 'Mehl' }, icon: '🌾', unit: 'kg', category: 'padaria_pastelaria' },

  // --- ARROZ / MASSA ---
  { id: 'arroz', names: { PT: 'Arroz', EN: 'Rice', ES: 'Arroz', FR: 'Riz', DE: 'Reis' }, icon: '🍚', unit: 'kg', category: 'arroz_massa' },
  { id: 'massa', names: { PT: 'Massa', EN: 'Pasta', ES: 'Pasta', FR: 'Pâtes', DE: 'Nudeln' }, icon: '🍝', unit: 'kg', category: 'arroz_massa' },
  { id: 'feijao', names: { PT: 'Feijão/Grão', EN: 'Beans', ES: 'Frijoles', FR: 'Haricots', DE: 'Bohnen' }, icon: '🫘', unit: 'kg', category: 'arroz_massa' },
  { id: 'cereais', names: { PT: 'Cereais', EN: 'Cereals', ES: 'Cereales', FR: 'Céréales', DE: 'Müsli' }, icon: '🥣', unit: 'emb', category: 'padaria_pastelaria' },

  // --- LATICÍNIOS ---
  { id: 'leite', names: { PT: 'Leite', EN: 'Milk', ES: 'Leche', FR: 'Lait', DE: 'Milch' }, icon: '🥛', unit: 'L', category: 'laticinios' },
  { id: 'queijo', names: { PT: 'Queijo', EN: 'Cheese', ES: 'Queso', FR: 'Fromage', DE: 'Käse' }, icon: '🧀', unit: 'kg', category: 'laticinios' },
  { id: 'manteiga', names: { PT: 'Manteiga', EN: 'Butter', ES: 'Mantequilla', FR: 'Beurre', DE: 'Butter' }, icon: '🧈', unit: 'emb', category: 'laticinios' },
  { id: 'ovos', names: { PT: 'Ovos', EN: 'Eggs', ES: 'Huevos', FR: 'Œufs', DE: 'Eier' }, icon: '🥚', unit: 'emb', category: 'laticinios' },
  { id: 'iogurte', names: { PT: 'Iogurte', EN: 'Yogurt', ES: 'Yogur', FR: 'Yaourt', DE: 'Joghurt' }, icon: '🍦', unit: 'unid', category: 'laticinios' },
  { id: 'natas', names: { PT: 'Natas', EN: 'Cream', ES: 'Nata', FR: 'Crème', DE: 'Sahne' }, icon: '🥛', unit: 'emb', category: 'laticinios' },

  // --- CONGELADOS ---
  { id: 'gelado', names: { PT: 'Gelado', EN: 'Ice Cream', ES: 'Helado', FR: 'Glace', DE: 'Eis' }, icon: '🍦', unit: 'emb', category: 'congelados' },
  { id: 'pizza', names: { PT: 'Pizza', EN: 'Pizza', ES: 'Pizza', FR: 'Pizza', DE: 'Pizza' }, icon: '🍕', unit: 'unid', category: 'congelados' },
  { id: 'gelo', names: { PT: 'Gelo', EN: 'Ice', ES: 'Hielo', FR: 'Glaçons', DE: 'Eiswürfel' }, icon: '🧊', unit: 'emb', category: 'congelados' },

  // --- BEBIDAS ---
  { id: 'agua', names: { PT: 'Água', EN: 'Water', ES: 'Agua', FR: 'Eau', DE: 'Wasser' }, icon: '💧', unit: 'L', category: 'bebidas' },
  { id: 'vinho', names: { PT: 'Vinho', EN: 'Wine', ES: 'Vino', FR: 'Vin', DE: 'Wein' }, icon: '🍷', unit: 'L', category: 'bebidas' },
  { id: 'cerveja', names: { PT: 'Cerveja', EN: 'Beer', ES: 'Cerveza', FR: 'Bière', DE: 'Bier' }, icon: '🍺', unit: 'L', category: 'bebidas' },
  { id: 'sumo', names: { PT: 'Sumo/Refrigerante', EN: 'Juice/Soda', ES: 'Zumo/Refresco', FR: 'Jus/Soda', DE: 'Saft/Limo' }, icon: '🥤', unit: 'L', category: 'bebidas' },
  { id: 'cafe', names: { PT: 'Café', EN: 'Coffee', ES: 'Café', FR: 'Café', DE: 'Kaffee' }, icon: '☕', unit: 'kg', category: 'bebidas' },
  { id: 'cha', names: { PT: 'Chá', EN: 'Tea', ES: 'Té', FR: 'Thé', DE: 'Tee' }, icon: '🍵', unit: 'emb', category: 'bebidas' },
  { id: 'espumante', names: { PT: 'Espumante', EN: 'Sparkling Wine', ES: 'Espumoso', FR: 'Pétillant', DE: 'Sekt' }, icon: '🍾', unit: 'L', category: 'bebidas' },
  { id: 'bebidas_esp', names: { PT: 'Bebidas Espirituosas', EN: 'Spirits', ES: 'Espirituosas', FR: 'Spiritueux', DE: 'Spirituosen' }, icon: '🍸', unit: 'L', category: 'bebidas' },

  // --- TEMPEROS ---
  { id: 'azeite', names: { PT: 'Azeite', EN: 'Olive Oil', ES: 'Aceite Oliva', FR: 'Huile Olive', DE: 'Olivenöl' }, icon: '🫒', unit: 'L', category: 'azeites' },
  { id: 'oleo', names: { PT: 'Óleo', EN: 'Oil', ES: 'Aceite', FR: 'Huile', DE: 'Öl' }, icon: '🌻', unit: 'L', category: 'azeites' },
  { id: 'vinagre', names: { PT: 'Vinagre', EN: 'Vinegar', ES: 'Vinagre', FR: 'Vinaigre', DE: 'Essig' }, icon: '🍶', unit: 'L', category: 'azeites' },
  { id: 'sal', names: { PT: 'Sal', EN: 'Salt', ES: 'Sal', FR: 'Sel', DE: 'Salz' }, icon: '🧂', unit: 'kg', category: 'azeites' },
  { id: 'especiarias', names: { PT: 'Especiarias', EN: 'Spices', ES: 'Especias', FR: 'Épices', DE: 'Gewürze' }, icon: '🌶️', unit: 'emb', category: 'azeites' },
  { id: 'molhos', names: { PT: 'Molhos', EN: 'Sauces', ES: 'Salsas', FR: 'Sauces', DE: 'Soßen' }, icon: '🥫', unit: 'emb', category: 'azeites' },

  // --- DOCES ---
  { id: 'chocolate', names: { PT: 'Chocolate', EN: 'Chocolate', ES: 'Chocolate', FR: 'Chocolat', DE: 'Schokolade' }, icon: '🍫', unit: 'unid', category: 'doces' },
  { id: 'gomas', names: { PT: 'Gomas/Doces', EN: 'Candies', ES: 'Chuches', FR: 'Bonbons', DE: 'Süßigkeiten' }, icon: '🍬', unit: 'emb', category: 'doces' },
  { id: 'pipocas', names: { PT: 'Pipocas', EN: 'Popcorn', ES: 'Palomitas', FR: 'Pop-corn', DE: 'Popcorn' }, icon: '🍿', unit: 'emb', category: 'doces' },
  { id: 'snacks', names: { PT: 'Snacks Salgados', EN: 'Salty Snacks', ES: 'Aperitivos', FR: 'Snacks Salés', DE: 'Salzige Snacks' }, icon: '🥔', unit: 'emb', category: 'doces' },
  { id: 'mel', names: { PT: 'Mel/Compota', EN: 'Honey/Jam', ES: 'Miel/Mermelada', FR: 'Miel/Confiture', DE: 'Honig/Marmelade' }, icon: '🍯', unit: 'emb', category: 'doces' },
  { id: 'acucar', names: { PT: 'Açúcar', EN: 'Sugar', ES: 'Azúcar', FR: 'Sucre', DE: 'Zucker' }, icon: '🧂', unit: 'kg', category: 'doces' },

  // --- LIMPEZA ---
  { id: 'det_loica', names: { PT: 'Detergente Loiça', EN: 'Dish Soap', ES: 'Lavavajillas', FR: 'Liquide Vaisselle', DE: 'Spülmittel' }, icon: '🧼', unit: 'emb', category: 'limpeza' },
  { id: 'det_roupa', names: { PT: 'Tratamento Roupa', EN: 'Laundry Detergent', ES: 'Detergente Ropa', FR: 'Lessive', DE: 'Waschmittel' }, icon: '🧺', unit: 'emb', category: 'limpeza' },
  { id: 'limpeza_casa', names: { PT: 'Limpeza Casa', EN: 'House Cleaning', ES: 'Limpieza Hogar', FR: 'Nettoyage Maison', DE: 'Hausreinigung' }, icon: '🪟', unit: 'emb', category: 'limpeza' },
  { id: 'esfregao', names: { PT: 'Utensílios Limpeza', EN: 'Cleaning Tools', ES: 'Utensilios Limpieza', FR: 'Outils Nettoyage', DE: 'Reinigungswerkzeuge' }, icon: '🧽', unit: 'unid', category: 'limpeza' },
  { id: 'vassoura', names: { PT: 'Vassoura/Aspirador', EN: 'Broom/Vacuum', ES: 'Escoba/Aspiradora', FR: 'Balai/Aspirateur', DE: 'Besen/Staubsauger' }, icon: '🧹', unit: 'unid', category: 'limpeza' },
  { id: 'sacos_lixo', names: { PT: 'Sacos Lixo', EN: 'Trash Bags', ES: 'Bolsas Basura', FR: 'Sacs Poubelle', DE: 'Müllbeutel' }, icon: '🗑️', unit: 'emb', category: 'limpeza' },
  { id: 'papel_alum', names: { PT: 'Papel Alumínio/Película', EN: 'Foil/Wrap', ES: 'Papel Aluminio/Film', FR: 'Aluminium/Film', DE: 'Alufolie/Folie' }, icon: '🗞️', unit: 'emb', category: 'limpeza' },

  // --- HIGIENE ---
  { id: 'papel_hig', names: { PT: 'Papel Higiénico', EN: 'Toilet Paper', ES: 'Papel Higiénico', FR: 'Papier Toilette', DE: 'Toilettenpapier' }, icon: '🧻', unit: 'emb', category: 'higiene' },
  { id: 'cabelo', names: { PT: 'Cabelo', EN: 'Hair Care', ES: 'Cuidado Cabello', FR: 'Soins Cheveux', DE: 'Haarpflege' }, icon: '🧴', unit: 'emb', category: 'higiene' },
  { id: 'banho', names: { PT: 'Banho', EN: 'Bath/Shower', ES: 'Baño/Ducha', FR: 'Bain/Douche', DE: 'Bad/Dusche' }, icon: '🧼', unit: 'emb', category: 'higiene' },
  { id: 'oral', names: { PT: 'Higiene Oral', EN: 'Oral Hygiene', ES: 'Higiene Oral', FR: 'Hygiène Buccale', DE: 'Mundhygiene' }, icon: '🪥', unit: 'emb', category: 'higiene' },
  { id: 'cremes', names: { PT: 'Cremes', EN: 'Creams', ES: 'Cremas', FR: 'Crèmes', DE: 'Cremes' }, icon: '🧴', unit: 'emb', category: 'higiene' },
  { id: 'desodorizante', names: { PT: 'Desodorizante/Perfume', EN: 'Deodorant/Perfume', ES: 'Desodorante/Perfume', FR: 'Déodorant/Parfum', DE: 'Deo/Parfüm' }, icon: '🌸', unit: 'unid', category: 'higiene' },
  { id: 'barba', names: { PT: 'Barbear', EN: 'Shaving', ES: 'Afeitado', FR: 'Rasage', DE: 'Rasur' }, icon: '🪒', unit: 'emb', category: 'higiene' },
  { id: 'higiene_fem', names: { PT: 'Higiene Feminina', EN: 'Feminine Hygiene', ES: 'Higiene Femenina', FR: 'Hygiène Féminine', DE: 'Damenhygiene' }, icon: '🩸', unit: 'emb', category: 'higiene' },
  { id: 'bebe', names: { PT: 'Bebé', EN: 'Baby', ES: 'Bebé', FR: 'Bébé', DE: 'Baby' }, icon: '👶', unit: 'emb', category: 'higiene' },

  // --- ANIMAIS ---
  { id: 'cao', names: { PT: 'Cão', EN: 'Dog', ES: 'Perro', FR: 'Chien', DE: 'Hund' }, icon: '🐶', unit: 'emb', category: 'outros' },
  { id: 'gato', names: { PT: 'Gato', EN: 'Cat', ES: 'Gato', FR: 'Chat', DE: 'Katze' }, icon: '🐱', unit: 'emb', category: 'outros' }
];
